name: flutter_screenutil_enhanced
description: A flutter plugin for adapting screen and font size.Guaranteed to look good on different models
version: 5.6.0
homepage: https://github.com/Pioneer-Linzi/flutter_screenutil_enhanced

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
